version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: firstlight
      POSTGRES_PASSWORD: password
      POSTGRES_DB: firstlightdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ../apps/api-server
    environment:
      DATABASE_URL: postgres://firstlight:password@postgres:5432/firstlightdb
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build: ../apps/web-client
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:4000

  electron:
    build: ../apps/electron-app
    ports:
      - "8080:8080"
    environment:
      ELECTRON_API_URL: http://localhost:4000

volumes:
  postgres-data:
